name: mapping_and_qc
description: Run STAR and QC
argument_groups:
  - name: Input arguments
    arguments:
      - name: --input_r1
        type: file
        direction: input
        required: true
      - name: --input_r2
        type: file
        direction: input
        required: true
      - name: --reference
        type: file
        required: true
  - name: Output arguments
    arguments:
      - name: --multiqc_output
        type: file
        example: multiqc.html
        direction: output
        required: true

resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf


dependencies:
  - name: cutadapt
    repository: bb
  - name: pear
    repository: bb
  - name: falco
    repository: bb
  - name: multiqc
    repository: bb
  - name: star/star_align_reads
    repository: bb
  - name: samtools/samtools_stats
    repository: bb

repositories:
  - name: bb
    type: vsh
    repo: vsh/biobox
    tag: main
runners:
  - type: nextflow

engines:
  - type: native
