name: samtools_5

arguments:
  - name: --input
    type: file
    required: true
  - name: --output
    type: file
    required: true
    direction: output

resources:
  - type: bash_script
    path: script.sh

engines:
  - type: docker
    image: quay.io/biocontainers/samtools:1.19.2--h50ea8bc_1

runners:
- type: executable
